### ISSUE TITLE
Can't damage celestial pillars in multiplayer

### ISSUE THREAD

**Issue by xdMatthewbx** [VVV101/AlchemistNPC#11]
Been doing a playthrough with a couple buddies. And we noticed that when we defeated the cultist and went to take out the pillars, they weren't taking any damage.

Did some testing (trying without certain mods, took a while since we have like 20) and narrowed it down to this mod (its fixed when this mod is disabled).

Also tried using the content disabler, still not working.

I've looked through the source code for any references to the pillars but haven't had much luck :/

**Comment by VVV101** [comment]
Found the problem. Fix would be uploaded in the next update.
Was in method PreAI. Fix looks like this.
`public override void ModifyHitPlayer(Projectile projectile, Player target, ref int damage, ref bool crit)	
		{
			for (int k = 0; k < 200; k++)
			{
				NPC npc = Main.npc[k];
				if (npc.HasBuff(mod.BuffType("CurseOfLight")) && (Main.rand.Next(4) == 0))
				{
					damage /= 2;
				}
			}
		}`
