### ISSUE TITLE
"In-game: Little Witch Bitch" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [VVV101/AlchemistNPC#13]
Mods: AlchemistNPC 7.4.1, Antisocial 1.0.1, Boss Checklist 0.1.6.1, Calamity Mod 1.3.4.1, Dark-Assassin's Mod Library (DALib) 1.1.1, Death Screen Countdown 0.15, Elements Awoken 1.3.5, Fargo's Mutant Mod: Summons and Souls 0.16.2, Yet Another Boss Health Bar 1.3.2, Beyond The Forgotten Ages 0.4.2.1, Full Health Respawn 0.0.1, Mod Helpers 2.1.0.2, imkSushi's Mod 4.3.1, JoostMod 0.7.2.9, [c/f2ce05:The Enigma Mod!] 0.12, Even More Modifiers 0.1.2.1, Magic Storage 0.4.3.3, MaxStackPlus 3.2, MorePotions(43 new potions) 3.300, No Angler Timer 0.1.2, Ocram 'n Stuff 1.0.1.9, OmniSwing 2.1, Peculiarity 0.7.2.2, Player Health and Mana Bars 1.0.1, The Pure Spirit Mod 0.1.1, Recipe Browser 0.7, Spirit Mod 1.3.4.1, Thorium Mod 1.5.0.4, Tremor Mod Remastered 1.3.2.7, Ultraconyx Mod 2.0.0.1, Varia (Open Beta) 1.0.2, VeinMiner 1.3.0.5, Wing Slot 1.6.1, WorldGen Previewer 0.1.5.1, Wormholes 1.8.1.1
 
Is day: False, Time of day/night: 7699, Elapsed half days: 229
 
World name: oOF, world size: Large
 
World progress: Eye of Cthulhu killed, King Slime killed, Queen Bee killed, Brain of Cthulhu killed, Skeletron killed, Wall of Flesh killed, Destroyer killed, Twins killed, Skeletron Prime killed, Plantera killed, Golem killed, Ancient Cultist killed
 
Items on ground: 385, Npcs active: 39
 
Player info: Name: `Dr. Clump`, Male: True, Demon Heart: True, Difficulty mode: 0, Life: 229 of 440 (200), Mana: 206 of 206, Defense: 100
 
Player equips: Head: Laetitia Ribbon (O-01-67), Body: Laetitia Coat (O-01-67), Legs: Laetitia Leggings (O-01-67), Accessory: Angry Stone of Hope, Accessory: Master Ninja Gear, Accessory: Boook's Mana Flower, Accessory: Occultist's Essence, Accessory: Quick Shield of Flesh, Accessory: Siren's Heart (Green), Vanity: Doge Mask, Vanity: Lunar Cultist Robe, Vanity: Armored Brain of Confusion, Vanity: Angel Halo, Vanity: Precise Statis' Blessing, Vanity: Laudanum, Vanity: Hasty Summoner Spark, Vanity: Angry Spooky Enchantment
 
Player count: 2 (multiplayer)
 
 
 
Recent error logs:
```
Beyond The Forgotten Ages: TreeMan. You have set ModNPC.banner or ModNPC.bannerItem, but not the other. Make sure you set both, check your spelling, and that the item exists if you are using mod.ItemType(). Report this to the Beyond The Forgotten Ages developers.
Beyond The Forgotten Ages: MysteriousAlienSpacecraft. You have set ModNPC.banner or ModNPC.bannerItem, but not the other. Make sure you set both, check your spelling, and that the item exists if you are using mod.ItemType(). Report this to the Beyond The Forgotten Ages developers.
0:000:00000 - 000011.39   Mod versions successfully retrieved and cached.
```
 
Make Little Witch Monster Summon Auto/Remove him

**Comment by VVV101** [comment]
Maybe in the next update, not earlier.

**Comment by hamstar0** [comment]
Just to note: I haven't implemented a way to reply to the sender of these.

**Comment by VVV101** [comment]
Fixed
