### ISSUE TITLE
"In-game: alchemist mod" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [VVV101/AlchemistNPC#15]
Mods: AlchemistNPC 7.6.1, Auto Trash 0.3.1, Boss Checklist 0.1.6.1, Calamity Mod 1.3.4.1, Prefixes For Enemies 2.0.0, Fargo's Mutant Mod: Summons and Souls 0.16.2, Full Health Respawn 0.0.1, Mod Helpers 3.1.0.4, Infinity - Endless Items 19.0, JoostMod 0.7.2.12, MaxStackPlus 3.2, Merchants+ (Beta) 0.6.7, Recipe Browser 0.7, Reduced Grinding 4.32, The One Library 0.4.1, Thorium Mod 1.5.0.4, VeinMiner 1.3.0.5, WeaponOut 1.6.3, Wing Slot 1.6.2
 
Is day: True, Time of day/night: 53158, Elapsed half days: 0
 
World name: playthrough 1, world size: Large
 
World progress: 
 
Items on ground: 11, Npcs active: 10
 
Player info: Name: `playthrough 1`, Male: True, Demon Heart: False, Difficulty mode: 0, Life: 100 of 100, Mana: 40 of 40, Defense: 2
 
Player equips: Accessory: Family Heirloom, Accessory: Shoe Spikes, Accessory: Hard Band of Regeneration
 
Player count: 1 (multiplayer)
 
 
 
Recent error logs:
```
No error logs available.
```
 
cant spawn bill cyhper

**Comment by VVV101** [comment]
Known issue. Happens because Calamity mod is not ON. Will fix it.
