### ISSUE TITLE
"In-game: one filling invetory quickly please help" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [VVV101/AlchemistNPC#6]
Mods: Agherium Mod 0.5.4.7, AlchemistNPC 6.1.1, The Antiaris 0.1.0.4, Auto Trash 0.2.1.3, Beast 1.0.6, Boss Checklist 0.1.5.3, Cheat Sheet 0.3.1, Crystilium 11.3.1.5, JereTheJuggler's Custom Generation 1.1, More Dialogue 0.2, Disarray 2.0.5.9, Enchanted Jewels 1.1.1, Erilipah 0.8.8.2, Exodus Mod 1.1, Expeditions Base 2.3.1, Expeditions Content Pack 1.2.2, The Far Lands Mod 0.1.0.8, FinalFantasyStuff 1.0.4, Yet Another Boss Health Bar 1.2.1, Gambler NPC 0.1, Hamstar's Helpers 1.4.8, Magic Wands! 0.89, Expeditions Addon : Interactions 0.1.2.1, Infinity - Endless Items 17.1, Kalciphoz's RPG Mod 1.2.1, The Enigma Mod 0.10.0.6, LightPets 1.0.4, Magic Storage 0.4.3.1, MaxStackMinus 0.2, MaxStackPlus 3.2, MoreAccesories+ 2.1, More Chest Loot 0.6, Mysterious Altars 1.0.1, pinkymod 0.74.0.6, Rainbow Rain 1.0.0, Recipe Browser 0.5, Sorcerer's Seceret 0.8.4.1, The Split Mod 0.2.1, The Luggage 0.1.3, Wing Slot 1.3.2, Wireless 1.4, Which Mod Is This From? 2.4, Wormholes 1.8.0
 
Is day: True, Time of day/night: 8922, Elapsed half days: 6
 
World name: Magic Mod Pack, world size: Large
 
World progress: 
 
Items on ground: 14, Npcs active: 14
 
Player info: Name: `MinaSaber`, Male: True, Demon Heart: False, Difficulty mode: 0, Life: 160 of 160 (100) (20), Mana: 24 of 24, Defense: 5
 
Player equips: Accessory: Sturdy Tower Shield, Accessory: Hexproof Aglet
 
Player count: 1 (single-player)
 
 
 
Recent error logs:
```
No error logs available.
```
 
items not stacking

**Comment by somebody0214** [comment]
MAX STACK MINUS

ср, 16 мая 2018 г., 3:51 hamstar <notifications@github.com>:

**Comment by VVV101** [comment]
Strange. What items are not stacking? I was using MaxStackPlus and don't see any problems with stacking.

**Comment by somebody0214** [comment]
read the description to max stack minus.
It makes all items unstackable and it is a joke mod. Why you even dowloaded
it in the first place?

чт, 17 мая 2018 г., 13:16 VVV101 <notifications@github.com>:

**Comment by VVV101** [comment]
This wasn't because of AlchemistNPC. Closed.
